name: CI

on:
  push:
    branches:
      - main
      - test
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20.19.2-alpine
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run test:ci
    - run: npm run test:report:coverage
