name: CI

on:
  push:
    branches:
      - main
      - test
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:20.19.2-alpine
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: "node_modules-${{ hashFiles('package-lock.json') }}"
    - run: ls src/lib/__tests__; npm ci; ls src/lib/__tests__

  spellcheck:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: node:20.19.2-alpine
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: "node_modules-${{ hashFiles('package-lock.json') }}"
        lookup-only: true
    - run: ls src/lib/__tests__; npm ci
    - run: npm run spellcheck; ls src/lib/__tests__

  build:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: node:20.19.2-alpine
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: "node_modules-${{ hashFiles('package-lock.json') }}"
        lookup-only: true
    - uses: actions/cache@v4
      with:
        path: "**/dist"
        key: "dist-${{ hashFiles('**/*.ts', '**/*.mts') }}"
    - run: ls src/lib/__tests__; npm ci
    - run: npm run build; ls src/lib/__tests__

  lint:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: node:20.19.2-alpine
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: "node_modules-${{ hashFiles('package-lock.json') }}"
        lookup-only: true
    - run: ls src/lib/__tests__; npm ci
    - run: npm run lint; ls src/lib/__tests__

  test:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: node:20.19.2-alpine
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: "node_modules-${{ hashFiles('package-lock.json') }}"
        lookup-only: true
    - run: ls src/lib/__tests__; npm ci; ls src/lib/__tests__
    - run: ls src/lib/__tests__; npm run test:ci; ls src/lib/__tests__
    - run: npm run test:report:coverage
